### ISSUE TITLE
Conduct April 1st-4th compensation request voting

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/growth#116]
_(previous voting round: #222 )_

 - [ ] Announce call for requests 3 days ahead and provide instructions on how to submit in a comment on this issue
 - [ ] Announce that the review period (1st) has begun in a comment on this issue
 - [ ] Transcribe [compensation requests](https://github.com/bisq-network/compensation/issues) to [stake and voting spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=820601546)
 - [ ] Announce that the voting period (2nd - 4th) has begun in a comment on this issue (also: created Slack reminder)
 - [ ] Wait for the voting period to complete
 - [ ] Review all edits to the spreadsheet to ensure there weren't any mistakes, etc
 - [ ] Protect this month's spreadsheet worksheet such that only the @bisq-network/compensation-maintainers can edit it
 - [ ] Announce that the voting period is complete in a comment below (see prior months' voting epics for examples)
 - [ ] Close all related compensation request issues with a comment  (see prior months' compensation requests for examples)
 - [ ] Complete any tasks in the comments below
